=== znichola/notre_cuisine_vegetal/schema/schema.json
{
  "$ref": "#/definitions/Recipie",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Recipie": {
      "additionalProperties": false,
      "properties": {
        "cookingTime": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "subtitle": {
          "type": "string"
        },
        "prepTime": {
          "type": "string"
        },
        "servs": {
          "type": "string"
        },
        "sections": {
          "items": {
            "$ref": "#/definitions/Section"
          },
          "type": "array"
        }
      },
      "required": [
        "title",
        "subtitle",
        "sections"
      ],
      "type": "object"
    },
    "Section": {
      "additionalProperties": false,
      "properties": {
        "title": {
          "type": "string"
        },
        "ingredients": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "instructions": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "title",
        "ingredients",
        "instructions"
      ],
      "type": "object"
    },
    "Ingredient": {
      "additionalProperties": false,
      "properties": {
        "qt": {
          "type": "number"
        },
        "unit": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "qt",
        "unit",
        "name"
      ],
      "type": "object"
    }
  }
}

=== znichola/notre_cuisine_vegetal/database/polenta_cremeuse.json
{
  "title": "Polenta crémeuse",
  "subtitle": "Comme Camille aime, un potenta bien crémeuse. Mais du coup difice a fair bien.",
  "servs": "2 personne",
  "sections": [
    {
      "title": "Preparation",
      "ingredients": [
        "100 g de semoule de maïs (polenta express)",
        "15 g de beurre",
        "300 ml d’eau",
        "200 ml de crème liquide (ou de lait pour une version plus légère)",
        "1 pincée de sel",
        "1 pincée de poivre",
        "15 g de beurre, ou, pour rester dans un mode cuisine italienne, de mascarpone."
      ],
      "instructions": [
        "Mettez le beurre dans la casserole et laissez-le fondre à feu doux.",
        "Versez la polenta dans la casserole, mélangez-la avec le beurre et laissez-la roussir une trentaine de secondes.",
        "Ajoutez l’eau et la crème, puis laissez cuire en mélangeant constamment pendant quelques minutes. Attendez que la polenta se décolle des parois de la casserole.",
        "Ajoutez à ce moment-là le sel, ainsi que le beurre aromatisé au piment d’Espelette ou le mascarpone. Mélangez bien.",
        "Servez immédiatement pour une dégustation optimale. Attention à ne pas trop la cuire, sinon elle deviendra moins légère."
      ]
    }
  ]
}
